name: Check Variables

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  check_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Check Variables
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        run: |
          if [[ -z "${UNITY_LICENSE}" ]]; then
            echo "UNITY_LICENSE is not set. Please set the secret in the repository settings."
            exit 1
          fi
          if [[ -z "${UNITY_EMAIL}" ]]; then
            echo "UNITY_EMAIL is not set. Please set the secret in the repository settings."
            exit 1
          fi
          if [[ -z "${UNITY_PASSWORD}" ]]; then
            echo "UNITY_PASSWORD is not set. Please set the secret in the repository settings."
            exit 1
          fi
