name: Deploy To Itch
on:
 workflow_dispatch

jobs:  
 deployPages:
   needs: buildWebGL
   name: Deploy to Itch.io 🚀
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - uses: actions/download-artifact@v2
       with:
         name: build-WebGL
         path: build

     - name: Display structure of root files
       run: ls -R
       working-directory: build/WebGL

     - name: Deploy 🚀
       uses: JamesIves/github-pages-deploy-action@4.1.4
       with:
         branch: itch-io
         folder: build/WebGL
         
     - uses: manleydev/butler-publish-itchio-action@master
       env:
         BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
         CHANNEL: HTML
         ITCH_GAME: ITCH-HELLOWORLD
         ITCH_USER: mittomrum
         BRANCH: itch-io
         PACKAGE: build/WebGL